### ISSUE TITLE
Get Unexpected interactiveMode: when running app with Gradle.

### ISSUE THREAD

**Issue by mitchelldehaven** [kermitt2/entity-fishing#111]
I was using the maven build previously and switched to the Gradle build. First time running appRun resulted in the following output: 
`> Task :appRun
Unexpected interactiveMode: `
I think the culprit is `interactiveMode = ''` in `build.gradle`, as removing that line allows it to launch successfully.

**Comment by kermitt2** [comment]
Thank you @mitchelldehaven !
Normally this message has no consequence, everything works fine. 
If we remove this line `interactiveMode = ''`, we have gradle running in interactive mode and this message:

> Press any key to stop the server.

and indeed when we press any keys, the server stops, which I find particularly unpleasant... so I neutralize the interactive mode with the  `interactiveMode = '' line. However then I didn't find a way to avoid having the 

> Task :appRun Unexpected interactiveMode: 

in the console. But as it has no consequence, it's not really a concern I think.

**Comment by mitchelldehaven** [comment]
Ah, perhaps I was mistaken. I thought when this message showed I could not access the web interface. Thanks!
