### ISSUE TITLE
Need help to checkout, corupt data?

### ISSUE THREAD

**Issue by Slashdacoda** [kermitt2/entity-fishing#120]
![image](https://user-images.githubusercontent.com/22930947/114382342-8db35900-9b8c-11eb-99a9-36fb37f235a0.png)

![image](https://user-images.githubusercontent.com/22930947/114382394-9a37b180-9b8c-11eb-9210-c36d22d6bedf.png)

**Comment by kermitt2** [comment]
Hello @Slashdacoda !

I've just tried and have seen no problem:

```
lopez@work:~/tmp$ git clone https://github.com/kermitt2/entity-fishing
Cloning into 'entity-fishing'...
remote: Enumerating objects: 511, done.
remote: Counting objects: 100% (511/511), done.
remote: Compressing objects: 100% (291/291), done.
remote: Total 14526 (delta 222), reused 375 (delta 148), pack-reused 14015
Receiving objects: 100% (14526/14526), 611.58 MiB | 1.98 MiB/s, done.
Resolving deltas: 100% (6480/6480), done.
Updating files: 100% (2798/2798), done.
lopez@work:~/tmp$ 
```

What's your OS and version of git?

You can always try with the zip, you might be luckier, e.g.:

```bash
wget https://github.com/kermitt2/entity-fishing/archive/refs/heads/master.zip
```

**Comment by Slashdacoda** [comment]
Hey @kermitt2 

Win 10pro ()
![image](https://user-images.githubusercontent.com/22930947/114528622-79816180-9c49-11eb-93c7-879f3d7235f5.png)

**A bit troubleshooting:**

After updating to 2.31.1 (https://gitforwindows.org), still same in git bash:
![image](https://user-images.githubusercontent.com/22930947/114529586-628f3f00-9c4a-11eb-8343-009221969475.png)

On Windows Terminal:
![image](https://user-images.githubusercontent.com/22930947/114530609-62437380-9c4b-11eb-8207-472b8faf9d9f.png)

After installing Cygwin 2.905 (64 bit):
![image](https://user-images.githubusercontent.com/22930947/114531157-ee559b00-9c4b-11eb-8eb5-e449db82c2b0.png)

>>> I think this is an Windows/Filesystem related problem: https://brendanforster.com/notes/fixing-invalid-git-paths-on-windows/

Some character problem. In my case the msg is: 
![image](https://user-images.githubusercontent.com/22930947/114532352-0da0f800-9c4d-11eb-8162-ddac68b5dfdd.png)

The fix should be related to some path related character, maybe: 

`https://github.com/kermitt2/entity-fishing/blob/master/data/corpus/corpus-long/wikipedia/RawText/Alfred_Conkling_Coxe%2C_Sr.`

why this `%2C` >> `,` in a filename?

**Comment by Slashdacoda** [comment]
update: on other pc with windows 10 it works, thats wierd^^

**Comment by kermitt2** [comment]
Hello !

The data you are pointing to come from an external evaluation corpus "Wikipedia" created by: 

```
Zhe Cao, Tao Qin, Tie-Yan Liu, Ming-Feng Tsai, and Hang Li. Learning to rank: from pairwise approach to listwise approach. In Zoubin Ghahramani, editor, Machine Learning, Proceedings of the Twenty-Fourth International Conference (ICML 2007), Corvallis, Oregon, USA, June 20-24, 2007, volume 227 of ACM International Conference Proceeding Series, pages 129–136. ACM. DOI <https://doi.org/10.1145/1273496.1273513>.
```

and they use the Wikipedia article name as file name - bad practice for file portability, but it's not our choice. 

The file names are referenced in `data/corpus/corpus-long/wikipedia/wikipedia.xml`, `@docName`, that's it. 

I guess there is no problem to rename these files (this corpus is not very useful beyond old system comparison, and is not updated), just be sure to rename them also in the corresponding `wikipedia.xml` for consistency... PR welcome ! :)

**Comment by Slashdacoda** [comment]
The checkout problem should be fixed, thx for the support @kermitt2
