### ISSUE TITLE
installation issue on Ubuntu 

### ISSUE THREAD

**Issue by adna9** [kermitt2/entity-fishing#123]
Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find org.grobid:grobid-ner:0.6.0.
     Searched in the following locations:
       - file:/home/clab/.m2/repository/org/grobid/grobid-ner/0.6.0/grobid-ner-0.6.0.pom
       - file:/home/clab/.m2/repository/org/grobid/grobid-ner/0.6.0/grobid-ner-0.6.0.jar
       - https://repo.maven.apache.org/maven2/org/grobid/grobid-ner/0.6.0/grobid-ner-0.6.0.pom
       - https://repo.maven.apache.org/maven2/org/grobid/grobid-ner/0.6.0/grobid-ner-0.6.0.jar
       - https://jcenter.bintray.com/org/grobid/grobid-ner/0.6.0/grobid-ner-0.6.0.pom
       - https://jcenter.bintray.com/org/grobid/grobid-ner/0.6.0/grobid-ner-0.6.0.jar
       - https://dl.bintray.com/rookies/maven/org/grobid/grobid-ner/0.6.0/grobid-ner-0.6.0.pom
       - https://dl.bintray.com/rookies/maven/org/grobid/grobid-ner/0.6.0/grobid-ner-0.6.0.jar
       - file:/home/clab/Desktop/NERFISH/entity-fishing/lib/org/grobid/grobid-ner/0.6.0/grobid-ner-0.6.0.pom
       - file:/home/clab/Desktop/NERFISH/entity-fishing/lib/org/grobid/grobid-ner/0.6.0/grobid-ner-0.6.0.jar
     Required by:
         project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
2 actionable tasks: 1 executed, 1 up-to-date

**Comment by kermitt2** [comment]
Hello @adna9 !

grobid-ner version 0.6.2 is the currently used version:
https://github.com/kermitt2/entity-fishing/blob/master/build.gradle#L71

Have you updated/rebuild this project? https://github.com/kermitt2/grobid-ner

**Comment by adna9** [comment]
yes using current versions of both still getting same error

**Comment by kermitt2** [comment]
As there is no dependency with grobid-ner version 0.6.2 in the current project, you probably should clean/update entity-fishing.

**Comment by adna9** [comment]
let me try it thanks for prompt reply!

**Comment by dlauc** [comment]
@adna9 have you managed to resolve the problem, I'm getting the similar one

`> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not resolve org.grobid:grobid-ner:0.6.2.
     Required by:
         project :
      > Could not resolve org.grobid:grobid-ner:0.6.2.
         > Could not get resource 'https://dl.bintray.com/rookies/maven/org/grobid/grobid-ner/0.6.2/grobid-ner-0.6.2.pom'.
            > Could not GET 'https://dl.bintray.com/rookies/maven/org/grobid/grobid-ner/0.6.2/grobid-ner-0.6.2.pom'. Received status code 403 from server: Forbidden
   > Could not resolve org.grobid:grobid-trainer:0.6.2.
     Required by:
         project :
      > Could not resolve org.grobid:grobid-trainer:0.6.2.
         > Could not get resource 'https://dl.bintray.com/rookies/maven/org/grobid/grobid-trainer/0.6.2/grobid-trainer-0.6.2.pom'.
            > Could not GET 'https://dl.bintray.com/rookies/maven/org/grobid/grobid-trainer/0.6.2/grobid-trainer-0.6.2.pom'. Received status code 403 from server: Forbidden
   > Could not resolve org.grobid:grobid-core:0.6.2.
     Required by:
         project :
      > Could not resolve org.grobid:grobid-core:0.6.2.
         > Could not get resource 'https://dl.bintray.com/rookies/maven/org/grobid/grobid-core/0.6.2/grobid-core-0.6.2.pom'.
            > Could not GET 'https://dl.bintray.com/rookies/maven/org/grobid/grobid-core/0.6.2/grobid-core-0.6.2.pom'. Received status code 403 from server: Forbidden
`

**Comment by kermitt2** [comment]
@dlauc bintray has closed its package hosting service and apparently they are not keeping it in read only mode as they said :( 
But have you installed grobid-ner locally as indicated in the documentation?

Normally you should have the artifact in your local maven repo, for example:

```
lopez@work:~/entity-fishing$ ll ~/.m2/repository/org/grobid/grobid-ner/0.6.2/
total 78M
drwxrwxr-x  2 lopez lopez 4.0K Mar 22 03:45 ./
drwxrwxr-x 10 lopez lopez 4.0K Mar 22 03:45 ../
-rw-rw-r--  1 lopez lopez 123K Mar 22 03:44 grobid-ner-0.6.2.jar
-rw-rw-r--  1 lopez lopez  78M Mar 22 03:45 grobid-ner-0.6.2-onejar.jar
-rw-rw-r--  1 lopez lopez 7.3K Mar 22 03:45 grobid-ner-0.6.2.pom
``` 

So the bintray lookup should not take place in principle.

**Comment by dlauc** [comment]
Thanks, I've had 0.6.0 version, it works now. Thank you for the great project!
