### ISSUE TITLE
Linking wikipedia/wikidata with only ‘ner’

### ISSUE THREAD

**Issue by aa303554** [kermitt2/entity-fishing#125]
When only the ner parameter is used in mentions, we still get some links to wikidata/Wikipedia, but with a different visual representation.

![image](https://user-images.githubusercontent.com/25822546/116876530-ec647380-ac1c-11eb-867d-efb8b4d50245.png)

See ‘Suisse’ and ‘Ludlow’ in the example below.

![image](https://user-images.githubusercontent.com/25822546/116876586-030aca80-ac1d-11eb-8b4e-8eb3ae0e4d37.png)

Yet in the json, "Ludlow" and "Suisse" are similar.

How can there be a Wikipedia/Wikidata link without using the wikipedia parameter in mentions ?

**Comment by kermitt2** [comment]
Hi @aa303554 !

See the [documentation](https://nerd.readthedocs.io/en/latest/restAPI.html#mentions), the `mentions` refers to the step of collecting terms **to be disambiguated**: 
- `ner` means we consider terms witch are named entities
- `wikipedia` means we consider terms which are "labels" of pages in Wikipedia (as title, anchors, redirections)

Then all these terms are disambiguated against Wikipedia, so the "linking" is always present but for a different set of terms of interest. `mentions` simply define how to select terms which will be "linked". 

If it appears unclear, would it be a way to clarify the documentation?

**Comment by kermitt2** [comment]
I am closing the issue - as it is answered by the documentation. Feel free to re-open it if you still have some doubts or if you think it's possible to improve the documentation.
