### ISSUE TITLE
Bad formatting of json response

### ISSUE THREAD

**Issue by oterrier** [kermitt2/entity-fishing#141]
Sometimes the result returned by the term lookup endpoint is not a valid json response, some " characters are not escaped
You can try with the term "Anderson" for french

![Capture du 2022-02-09 17-07-20](https://user-images.githubusercontent.com/8970395/153241309-4dd050e7-29af-4ab4-b1df-333e6ec17ab4.png)
![Capture du 2022-02-09 17-06-32](https://user-images.githubusercontent.com/8970395/153241316-17b12b4c-d24e-4606-8ba5-8077d18da663.png)

`"preferred" : "Greg "Cadillac" Anderson"`

Best regards
Olivier

**Comment by kermitt2** [comment]
fix with 35fe86c03f82b38ab9f0c3e646af8def69dce681

![Screenshot from 2022-04-30 19-45-16](https://user-images.githubusercontent.com/2340795/166116541-af5fcc1d-4dbf-4b0a-8322-1018ec122aeb.png)
