### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by readefine-app** [kermitt2/entity-fishing#152]
Hi, just wondering if there are any updates on Dockerizing entity-fishing? I'd like to deploy my own version on GCP or Azure.

**Comment by kermitt2** [comment]
Hi @readefine-app 

Docker image is now available: see the [documentation](https://nerd.readthedocs.io/en/latest/docker.html) 

It is not tested on GCP or Azure, so any feedback very welcome !

(on my machine it works :) )

**Comment by readefine-app** [comment]
Thanks!
