### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by lfoppiano** [kermitt2/entity-fishing#21]
dependencies: 
 - grobid-home
 - grobid-ner models

**Comment by rautant** [comment]
Anyone planning to do this?
I for one would appreciate it.

**Comment by lfoppiano** [comment]
@rautant we had though about it a bit, however the problem there is that we would need to find a solution how to manage the huge amount of data for the knowledge base (~80Gb) which we cannot ship in the docker image itself.

**Comment by rautant** [comment]
Thanks for reply. What about a Dockerfile / docker-compose.yml?
I noticed that Grobid already has a Dockerfile (https://github.com/kermitt2/grobid/blob/master/Dockerfile).
