### ISSUE TITLE
Collapsible element for list of statements

### ISSUE THREAD

**Issue by kermitt2** [kermitt2/entity-fishing#38]
In the demo console, all the statements are listed in the infobox making it sometime ridiculously huge. We would need to put the statements in a collapsible element to have a cleaner infobox.

**Comment by tantikristanti** [comment]
Collapsible element for list of statements had beed added in 'nerd.new.js'. 

<img width="905" alt="screen shot 2018-09-27 at 17 15 23" src="https://user-images.githubusercontent.com/28044697/46156150-20af7080-c279-11e8-98f2-cf7e19da09c1.png">

**Comment by kermitt2** [comment]
With commit a05ccd72914c8a38b59486a7c25c12b6244d6d00, I made a bit of styling (removing padding and margin to gain space). I added a chevron icon so that it's more easy to apprehend the collapsible, but when the element is colapsed or not the icon should change as up or down - I've not added this behavior (there is an event to catch). 

There is something else which is not visually nice I think, we have a red dotted border appearing when the element is active - so basically a non-meaningful border which will appear and disappear with no reason, see below:

![screen shot 2018-09-28 at 13 26 41](https://user-images.githubusercontent.com/2340795/46205926-b6eba100-c322-11e8-99de-475db671a342.png)

**Comment by kermitt2** [comment]
The man issue is when viewing an annotated PDF. Opening the collapsible make the view moving to another part of the document - typically to the previous page or the next page, and we don't see anymore the page where we were, nor the infobox and its statement.

**Comment by lfoppiano** [comment]
I tested with a live demo in Lisbon and I didn't find any glitches or problems. 

@kermitt2 Can we close this issue?
