### ISSUE TITLE
Multiwords are not well recognised 

### ISSUE THREAD

**Issue by lfoppiano** [kermitt2/entity-fishing#54]
Multiwords are not well recognised 

e.g: 
```
{
    "text": "The Vichy regime was the French government which succeeded the Third Republic from July 1940 to August 1944. It was proclaimed by Marshal Philippe Pétain following the military defeat of France and the July 10 vote by the National Assembly to grant extraordinary powers to Pétain, who held the title of President of the Council.",
    "language": {
        "lang": "en"
    },
    "mentions": [
        "ner",
        "wikipedia"
    ],
    "nbest": false,
    "sentence": false,
    "customisation": "generic"
}
```
result in: 
<img width="594" alt="screen shot 2018-01-19 at 11 23 01" src="https://user-images.githubusercontent.com/15426/35146395-234ebd20-fd0b-11e7-9c45-f039a01575b8.png">

as compared with version 0.0.2: 
<img width="594" alt="screen shot 2018-01-19 at 11 23 32" src="https://user-images.githubusercontent.com/15426/35146413-34858628-fd0b-11e7-8ce3-d0672cbbb2d9.png">

**Comment by kermitt2** [comment]
It looks good. 
![screenshot from 2018-02-12 15-43-26](https://user-images.githubusercontent.com/2340795/36102188-db22f46c-100b-11e8-9c59-65500797feb2.png)

**Comment by lfoppiano** [comment]
Multiwords seems to work also in PDFs: 

<img width="1160" alt="screen shot 2018-03-01 at 15 54 13" src="https://user-images.githubusercontent.com/15426/36851238-15150efc-1d69-11e8-936f-5d5aa46d32e3.png">

<img width="1105" alt="screen shot 2018-03-01 at 15 45 48" src="https://user-images.githubusercontent.com/15426/36851264-24fd6ec2-1d69-11e8-9cff-f4ad0ecc9073.png">

**Comment by kermitt2** [comment]
There is a performance loss of around 3% f-score with species, I've started looking at it yesterday.
