### ISSUE TITLE
Misplaced display result in the sentence segmentation service

### ISSUE THREAD

**Issue by tantikristanti** [kermitt2/entity-fishing#73]
In the service of sentence segmentation, there are times that the sentences are misplaced on the display result even though they have some correct offsets.
Let’s take an example of a text of WW1, the result of the offsets are as follows:
```
{
    "sentences": [
        {
            "offsetStart": 0,
            "offsetEnd": 111
        },
        {
            "offsetStart": 111,
            "offsetEnd": 275
        },
        {
            "offsetStart": 275,
            "offsetEnd": 431
        },
        {
            "offsetStart": 431,
            "offsetEnd": 599
        },
        {
            "offsetStart": 599,
            "offsetEnd": 737
        },
        {
            "offsetStart": 737,
            "offsetEnd": 1033
        },
        {
            "offsetStart": 1033,
            "offsetEnd": 1318
        },
        {
            "offsetStart": 1318,
            "offsetEnd": 1387
        },
        {
            "offsetStart": 1387,
            "offsetEnd": 1456
        },
        {
            "offsetStart": 1456,
            "offsetEnd": 1603
        },
        {
            "offsetStart": 1603,
            "offsetEnd": 1758
        },
        {
            "offsetStart": 1758,
            "offsetEnd": 2033
        },
        {
            "offsetStart": 2033,
            "offsetEnd": 2199
        },
        {
            "offsetStart": 2199,
            "offsetEnd": 2388
        },
        {
            "offsetStart": 2388,
            "offsetEnd": 2567
        }
    ]
}
```
But they have the display results as follows:
<img width="1276" alt="screen shot 2018-03-20 at 14 25 46" src="https://user-images.githubusercontent.com/28044697/37657453-524f3608-2c4b-11e8-87b1-bd51b47a5ac5.png">

**Comment by tantikristanti** [comment]
The main causes of the wrong position in the sentence segmentation service are:
1. GET request does not maintain text formatting.
2. There are some hidden carraige returns "\r" in the text. 

The changes regarding this issue were done in the nerd.new.js, NerdRestService.java and ProcessText.java.

Currently, the result from the service can be seen like this:

<img width="1016" alt="screen shot 2018-09-28 at 16 03 59" src="https://user-images.githubusercontent.com/28044697/46213171-2f109180-c338-11e8-8dae-c50a9e6563d2.png">




The problem is fixed in the class ProcessText.java

**Comment by lfoppiano** [comment]
I think we can close this one
