### ISSUE TITLE
add a way to reduce the number of relatedness values stored for cache

### ISSUE THREAD

**Issue by lfoppiano** [kermitt2/entity-fishing#78]
After hammering the system for several hours, the cache containing the list of all calculated relatedness reach the heap memory limit, causing the GC to be triggered too often (high CPU). 

We should find an efficient solution to invalidate older element in this cache in order to keep the memory footprint lower.

**Comment by kermitt2** [comment]
Relatedness might disappear in version 0.0.4 for a LSTM-based architecture.

**Comment by lfoppiano** [comment]
the issue affect any batch process running for more than a day, a relatively simple cache implementation can be used via Guava https://github.com/google/guava/wiki/CachesExplained#caches

**Comment by tantikristanti** [comment]
Regarding this issue, the concept of cache is implemented in another branch called "cacheGuava". The implementation is done in a Relatedness class.

**Comment by lfoppiano** [comment]
Implemented in branch: https://github.com/kermitt2/entity-fishing/tree/cacheGuava

**Comment by tantikristanti** [comment]
Here are some tests that have been done so far with GoFishing:

<img width="1338" alt="screen shot 2018-11-15 at 15 50 49" src="https://user-images.githubusercontent.com/28044697/48560618-8968b000-e8ee-11e8-8666-7970eef06249.png">
