### ISSUE TITLE
Hypenization in PDF

### ISSUE THREAD

**Issue by kermitt2** [kermitt2/entity-fishing#8]
De-hypenization in PDF is a bit more complicated to manage than in text because we have to keep track of the coordinates via multiple layout tokens for a single text token.

**Comment by tantikristanti** [comment]
One example of this issue can be found in the Pdf file disambiguation service. 

The pdf file used as resource is : 
[ADSLSystemEnglish.pdf](https://github.com/kermitt2/nerd/files/1829806/ADSLSystemEnglish.pdf)

On the result, it is showed that a mention `mul-tiple` contains hypen. The mention is not recognized as one whole token but as two tokens `mul` and `tiple` and as if referring to two different entities. 

<img width="1262" alt="screen shot 2018-03-20 at 15 46 29" src="https://user-images.githubusercontent.com/28044697/37661805-e45793a6-2c55-11e8-8bef-29394f24c993.png">

**Comment by lfoppiano** [comment]
We should check whether the de-hypenisation improvement in grobid have any (hopefully) good impact on this example.

**Comment by kermitt2** [comment]
Looks good with current Grobid

![Screenshot from 2020-06-12 16-16-20](https://user-images.githubusercontent.com/2340795/84512334-1db41800-acc8-11ea-88e0-f5e0655e3ff1.png)
