### ISSUE TITLE
More metatadata in the JSON response

### ISSUE THREAD

**Issue by kermitt2** [kermitt2/entity-fishing#81]
Add in the JSON response a bit more metadata consistent with other tools:
```json
{ 
...
  "software": "entity-fishing",
  "version": "0.0.4",
   "date": "2018-05-02T12:24:55.529301",
...
}
(date is the date of generation of the response)

**Comment by tantikristanti** [comment]
Hello @kermitt2 ,

I tried to implement a bit regarding this issue in a branch `metadataJSON`. Below is the result, what do you think?

<img width="371" alt="screen shot 2018-10-18 at 17 03 32" src="https://user-images.githubusercontent.com/28044697/47164308-1886a600-d2f8-11e8-9cce-7964921c1c14.png">

**Comment by lfoppiano** [comment]
I add here, as mentioned in https://github.com/kermitt2/entity-fishing/commit/f30ea394d2b5041b7bcaccf147121cd909a65f54#commitcomment-30958982, we should add also an entry point in the API `/version` returning the version number (and the name, since we have also the name)

**Comment by tantikristanti** [comment]
An entry point `/version` in the API returning the name, the version number and the description has been added in the same branch `metadataJSON`.

<img width="381" alt="screen shot 2018-10-19 at 13 40 54" src="https://user-images.githubusercontent.com/28044697/47216308-c780bb80-d3a4-11e8-95fe-27af5206165d.png">

**Comment by tantikristanti** [comment]
Thanks for the input @lfoppiano  . All the fixes has been done in the same branches. I will make the pull request if everything is OK.
