### ISSUE TITLE
looks great, maybe a python version is more competitive and atractive

### ISSUE THREAD

**Issue by loveJasmine** [kermitt2/entity-fishing#89]

**Comment by lfoppiano** [comment]
Dear @loveJasmine, 
    I personally don't think the language makes the tool more or less competitive, however could you tell us what are your needs? Why would you need a python version?

**Comment by loveJasmine** [comment]
I believe that python are more supportive on many ML/DL package like tensorflow,torch,sciketlearn etc.
I think the neural network approach on NER and entity link will emerge.
I want be a contributor on this project if it is python base.

**Comment by lfoppiano** [comment]
All good reasons, however can't deep learning models can be developed in Python and used in Java?

**Comment by loveJasmine** [comment]
Great @kermitt2
