### ISSUE TITLE
Broken links to AWS (MacOS)

### ISSUE THREAD

**Issue by Lawliet-L** [kermitt2/entity-fishing#96]
Good day, guys, could you update links to get the data from AWS for macOS?
https://science-miner.s3.amazonaws.com/entity-fishing/0.0.3/macos/db-kb.zip (4.1 GB)
https://science-miner.s3.amazonaws.com/entity-fishing/0.0.3/macos/db-en.zip (5.5 GB)
https://science-miner.s3.amazonaws.com/entity-fishing/0.0.3/macos/db-es.zip (1.5 GB)
https://science-miner.s3.amazonaws.com/entity-fishing/0.0.3/macos/db-it.zip (1.3 GB)
I keep getting ```Status code:403``` the other 2 links are fine, same for all the Linux links.

**Comment by kermitt2** [comment]
Hello @Lawliet-L !
Thanks for the notification, I updated the permissions and it should be fine.

**Comment by Lawliet-L** [comment]
Works for me, thank you!

**Comment by kermitt2** [comment]
It looks that everything is working! I close the issue, but of course feel free to re-open it if you encounter any problems like this.
